baseurl:          /cu-ds1-2026-fall

# Permalinks
permalink:        pretty

# Setup
title:            'Distributed Systems Fundamentals'
tagline:          'Columbia University Course COMS 4113'
description:      'Fall 2026'
url:              http://frankeh.github.io

paginate:         1
paginate_path:    /cu-ds1-2026-fall/blog/page:num

# Custom vars
version:          0.1
